baseURL = "https://samkp06.github.io/Misfits-III/"
languageCode = "en-us"
title = "Sam Designs"
theme = "aether"
# googleAnalytics = "Your google analytics tracking ID - optional"

[params]
brand = "sam"
description = "A collection of illustrations by @sam.v"
bgimg = "img/background.png"

[markup.goldmark.renderer]
unsafe= true